/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function byteLength(input: string): number

export declare function fromByteArray(buf: Uint8Array): string

export declare function toByteArray(input: string): Uint8Array
